<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDyzvu7s\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDyzvu7s/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDyzvu7s.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDyzvu7s\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDyzvu7s\appProdProjectContainer([
    'container.build_hash' => 'Dyzvu7s',
    'container.build_id' => '9e52bf75',
    'container.build_time' => 1630933500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDyzvu7s');
